/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Usercomponent: typeof import('./src/components/user/Usercomponent.vue')['default']
    UserComponent: typeof import('./src/components/user/UserComponent.vue')['default']
    UserUserComponent: typeof import('./src/components/user/UserComponent.vue')['default']
  }
}
